
// GENERATED FILE - DO NOT MODIFY
//
// GENERATED BY GO:GENERATE AT 2019-03-10T15:51:34&#43;0800
//
// FILE GENERATED USING ~/generators/versioning/main.go

package main

const Version = "0.0.0"

const Commit = "934750f"

